# Generated by Django 6.0.3 on 2026-04-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("video", models.FileField(upload_to="videos/")),
            ],
        ),
        migrations.AddField(
            model_name="pandit",
            name="email",
            field=models.EmailField(default="rituraj0413@gmail.com", max_length=254),
            preserve_default=False,
        ),
    ]
