# Generated by Django 6.0.3 on 2026-04-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_birth_date_profile_birth_place_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_otp",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="profile",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
