# Generated by Django 6.0.3 on 2026-04-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_email_otp_profile_otp_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="receipt_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
