# Generated by Django 6.0.3 on 2026-04-11 19:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_booking_payment_completed_at_booking_receipt_sent_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="wallet_balance",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package_code",
                    models.CharField(
                        choices=[
                            ("starter_10", "First 10 Minutes"),
                            ("hourly_60", "1 Hour"),
                            ("unlimited_day", "1 Day Unlimited"),
                        ],
                        max_length=30,
                    ),
                ),
                ("package_name", models.CharField(max_length=100)),
                ("amount", models.PositiveIntegerField()),
                ("minutes_included", models.PositiveIntegerField(default=0)),
                ("unlimited_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
