# Generated by Django 6.0.3 on 2026-04-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_profile_wallet_balance_wallettransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="payment_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
