# Generated by Django 6.0.3 on 2026-04-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_wallettransaction_payment_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="consultation_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="consultation_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
